#!/usr/bin/env bash
# Regenerate API.md from nixdoc doc comments in lib/*.nix.
set -euo pipefail

OUT="${1:-API.md}"

{
  echo "# Bake Library API"
  echo
  echo "> Generated by \`scripts/gen-api-docs.sh\`. Do not edit by hand."
  echo

  nixdoc --category "core" \
    --description "Target construction and module validation." \
    --file lib/core.nix

  echo

  nixdoc --category "scope" \
    --description "Scope aggregation and bake file generation." \
    --file lib/scope.nix

  echo

  nixdoc --category "describe" \
    --description "Debugging helpers." \
    --file lib/describe.nix
} > "$OUT"
